version: "3.1"
services:
  redis:
    image: redis:alpine
    container_name: event-redis
    ports:
      - "6380:6379"

  mysql:
    image: mysql:5.7
    container_name: event-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=20187a63f0901ea878fc
      - MYSQL_DATABASE=event
      - MYSQL_USER=event
      - MYSQL_PASSWORD=event@2019#
    ports:
      - "3308:3306"

  php:
    image: khoada/php7-fpm-memcached
    container_name: event-php
    links:
      - mysql:mysql
      - redis:redis
    ports:
      - "9009:9000"
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  webserver:
    image: nginx
    container_name: event-webserver
    working_dir: /application
    links:
      - php:fpm
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8008:80"
